### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by ROCKFACEGEAR** [crelies/AdvancedList-SwiftUI#2]
So I'm getting an error message saying that this package is missing it's Package.swift manifest. How do I work around this and get it to load into my project using xCode?

**Comment by crelies** [comment]
Hey @ROCKFACEGEAR

I totally overlooked this issue... I'm sorry for that! This project is just an example app integrating my AdvancedList Swift package. But I'm pretty sure that you already know that today 😉
